version: '3'
services:
  minio:
    image: minio/minio
    entrypoint:
    - /bin/sh
    command:
    - -c
    - >
      mkdir -p /data/storage;
      minio server /data;
      exit 0
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
