name: Publish to TestPyPI and PyPI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
    - name: Tweak version for dev-release
      if: startsWith(github.ref, 'refs/tags') != true
      run: |
        echo -n $(cat appyter/VERSION).$(git rev-parse --short HEAD) > appyter/VERSION
    - name: Build binary wheel and source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
